import React, { useMemo, useState } from 'react';
import { CheckCircle2, Download, Lock, Minus, Plus, ShieldCheck, ShoppingBag, Trash2 } from 'lucide-react';
import { CartItem, CheckoutCustomer, OrderDelivery, OrderPayment, OrderRecord } from '../types';

interface CheckoutProps {
  cart: CartItem[];
  recentOrders: OrderRecord[];
  onIncreaseQty: (itemId: string) => void;
  onDecreaseQty: (itemId: string) => void;
  onRemoveItem: (itemId: string) => void;
  onPlaceOrder: (customer: CheckoutCustomer, payment: OrderPayment) => OrderRecord;
  onAttachDelivery: (orderId: string, delivery: OrderDelivery) => void;
  onContinueShopping: () => void;
}

interface CheckoutFormState extends CheckoutCustomer {
  agreeToTerms: boolean;
}

const INITIAL_FORM: CheckoutFormState = {
  fullName: '',
  email: '',
  country: '',
  addressLine: '',
  city: '',
  state: '',
  postalCode: '',
  agreeToTerms: false,
};

const formatMoney = (amount: number) => `$${amount.toFixed(2)}`;

const buildLocalDelivery = (order: OrderRecord): OrderDelivery => {
  const generatedAt = Date.now();
  const expiresAt = generatedAt + 10 * 365 * 24 * 60 * 60 * 1000;

  const uniqueItems = Array.from(
    new Map(order.items.map((line) => [line.item.id, line.item])).values(),
  );

  const links = uniqueItems.map((item) => {
    const content = [
      'Lumimar Library - Frontend Only Delivery',
      `Order ID: ${order.id}`,
      `Customer: ${order.customer.email}`,
      `Product: ${item.title}`,
      '',
      'This file is generated by the frontend-only checkout mode.',
      'No backend or payment gateway was called for this delivery.',
    ].join('\n');

    return {
      itemId: item.id,
      title: item.title,
      downloadUrl: `data:text/plain;charset=utf-8,${encodeURIComponent(content)}`,
      expiresAt,
    };
  });

  return {
    generatedAt,
    expiresAt,
    links,
  };
};

const Checkout: React.FC<CheckoutProps> = ({
  cart,
  recentOrders,
  onIncreaseQty,
  onDecreaseQty,
  onRemoveItem,
  onPlaceOrder,
  onAttachDelivery,
  onContinueShopping,
}) => {
  const [form, setForm] = useState<CheckoutFormState>(INITIAL_FORM);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [paymentError, setPaymentError] = useState<string | null>(null);
  const [completedOrder, setCompletedOrder] = useState<OrderRecord | null>(null);

  const subtotal = useMemo(
    () => cart.reduce((sum, cartItem) => sum + cartItem.item.price * cartItem.quantity, 0),
    [cart],
  );
  const paymentRequired = subtotal > 0;
  const tax = paymentRequired ? subtotal * 0.07 : 0;
  const total = subtotal + tax;

  const validate = () => {
    const nextErrors: Record<string, string> = {};
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!form.fullName.trim()) nextErrors.fullName = 'Full name is required.';
    if (!form.email.trim() || !emailPattern.test(form.email.trim())) nextErrors.email = 'Enter a valid email.';
    if (!form.country.trim()) nextErrors.country = 'Country is required.';
    if (!form.addressLine.trim()) nextErrors.addressLine = 'Address is required.';
    if (!form.city.trim()) nextErrors.city = 'City is required.';
    if (!form.state.trim()) nextErrors.state = 'State is required.';
    if (!form.postalCode.trim()) nextErrors.postalCode = 'Postal code is required.';
    if (!form.agreeToTerms) nextErrors.agreeToTerms = 'You must accept terms to continue.';

    return nextErrors;
  };

  const updateField = (field: keyof CheckoutFormState, value: string | boolean) => {
    setForm((prev) => ({ ...prev, [field]: value }));
    setErrors((prev) => {
      if (!prev[field]) return prev;
      const copy = { ...prev };
      delete copy[field];
      return copy;
    });
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setPaymentError(null);

    const nextErrors = validate();
    if (Object.keys(nextErrors).length > 0) {
      setErrors(nextErrors);
      return;
    }

    const customer: CheckoutCustomer = {
      fullName: form.fullName.trim(),
      email: form.email.trim(),
      country: form.country.trim(),
      addressLine: form.addressLine.trim(),
      city: form.city.trim(),
      state: form.state.trim(),
      postalCode: form.postalCode.trim(),
    };

    setIsSubmitting(true);

    try {
      const payment: OrderPayment = paymentRequired
        ? {
            status: 'paid',
            provider: 'none',
            currency: 'USD',
            reference: `LOCAL_${Date.now()}`,
          }
        : {
            status: 'not_required',
            provider: 'none',
            currency: 'USD',
          };

      const placed = onPlaceOrder(customer, payment);
      const delivery = buildLocalDelivery(placed);
      onAttachDelivery(placed.id, delivery);
      setCompletedOrder({ ...placed, delivery });
      setForm(INITIAL_FORM);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unable to complete checkout right now.';
      setPaymentError(message);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (completedOrder) {
    return (
      <section className="max-w-4xl mx-auto py-12 animate-in fade-in">
        <div className="bg-white border border-stone-100 rounded-[2rem] p-8 md:p-12 chic-shadow text-center">
          <div className="w-20 h-20 mx-auto rounded-full bg-green-50 text-green-600 flex items-center justify-center mb-6">
            <CheckCircle2 size={42} />
          </div>
          <p className="text-[10px] uppercase tracking-[0.2em] font-bold text-stone-500 mb-2">Order Confirmed</p>
          <h2 className="text-4xl font-serif font-bold text-stone-900 mb-4">Order Completed</h2>
          <p className="text-stone-500 max-w-2xl mx-auto mb-8">
            Your order <span className="font-bold text-stone-900">#{completedOrder.id}</span> is complete in frontend-only mode. Download links are ready below.
          </p>

          {completedOrder.delivery?.links?.length ? (
            <div className="max-w-2xl mx-auto bg-green-50 border border-green-100 rounded-2xl p-5 mb-8 text-left">
              <p className="text-[10px] font-bold uppercase tracking-widest text-green-700 mb-3">
                Access Links
              </p>
              <div className="space-y-3">
                {completedOrder.delivery.links.map((link) => (
                  <a
                    key={`${completedOrder.id}-${link.itemId}`}
                    href={link.downloadUrl}
                    download={`${link.title}.txt`}
                    className="flex items-center justify-between bg-white border border-green-200 rounded-xl px-4 py-3 text-sm text-stone-700 hover:bg-green-50 transition-colors"
                  >
                    <span className="font-medium">{link.title}</span>
                    <span className="inline-flex items-center gap-2 text-green-700 font-semibold">
                      Download
                      <Download size={14} />
                    </span>
                  </a>
                ))}
              </div>
            </div>
          ) : null}

          <div className="max-w-md mx-auto text-left bg-stone-50 rounded-2xl p-6 border border-stone-100 mb-8">
            <p className="text-[10px] font-bold uppercase tracking-widest text-stone-500 mb-4">Order Summary</p>
            <div className="space-y-2 text-sm text-stone-600">
              <div className="flex justify-between"><span>Subtotal</span><span>{formatMoney(completedOrder.subtotal)}</span></div>
              <div className="flex justify-between"><span>Tax</span><span>{formatMoney(completedOrder.tax)}</span></div>
              <div className="flex justify-between pt-2 border-t border-stone-200 font-bold text-stone-900">
                <span>Total</span><span>{formatMoney(completedOrder.total)}</span>
              </div>
              {completedOrder.payment.reference && (
                <div className="flex justify-between pt-2 border-t border-stone-200 text-xs">
                  <span>Order Ref</span>
                  <span className="font-mono text-stone-700">{completedOrder.payment.reference}</span>
                </div>
              )}
            </div>
          </div>

          <button
            onClick={() => {
              setCompletedOrder(null);
              onContinueShopping();
            }}
            className="bg-stone-900 text-white px-8 py-4 rounded-2xl text-xs font-bold uppercase tracking-widest hover:bg-stone-800 transition-all"
          >
            Continue Shopping
          </button>
        </div>
      </section>
    );
  }

  return (
    <section className="py-12 animate-in fade-in">
      <header className="mb-10">
        <h2 className="text-5xl md:text-6xl font-serif font-bold text-stone-900 tracking-tighter mb-3">Checkout</h2>
        <p className="text-stone-500 font-medium">Frontend-only checkout mode. No backend calls are made.</p>
      </header>

      {cart.length === 0 ? (
        <div className="bg-white border border-stone-100 rounded-[2rem] p-10 md:p-14 text-center chic-shadow">
          <ShoppingBag size={40} className="mx-auto text-stone-400 mb-4" />
          <h3 className="text-3xl font-serif font-bold text-stone-900 mb-3">Your Cart Is Empty</h3>
          <p className="text-stone-500 mb-8">Browse the library and add at least one item to start checkout.</p>
          <button
            onClick={onContinueShopping}
            className="bg-stone-900 text-white px-8 py-4 rounded-2xl text-xs font-bold uppercase tracking-widest hover:bg-stone-800 transition-all"
          >
            Browse Library
          </button>

          {recentOrders.length > 0 && (
            <div className="mt-12 max-w-xl mx-auto text-left">
              <p className="text-[10px] font-bold uppercase tracking-widest text-stone-500 mb-4">Recent Orders</p>
              <div className="space-y-3">
                {recentOrders.slice(0, 3).map((order) => (
                  <div key={order.id} className="bg-stone-50 border border-stone-200 rounded-2xl p-4 text-sm">
                    <div className="flex justify-between">
                      <span className="font-bold text-stone-900">#{order.id}</span>
                      <span className="text-stone-500">{new Date(order.createdAt).toLocaleDateString()}</span>
                    </div>
                    <p className="text-stone-500 mt-1">{order.items.reduce((sum, line) => sum + line.quantity, 0)} items</p>
                    {order.delivery?.links?.length ? (
                      <div className="mt-3 flex flex-wrap gap-2">
                        {order.delivery.links.map((link) => (
                          <a
                            key={`${order.id}-${link.itemId}`}
                            href={link.downloadUrl}
                            download={`${link.title}.txt`}
                            className="inline-flex items-center gap-2 rounded-lg border border-stone-300 bg-white px-3 py-1.5 text-[11px] font-semibold text-stone-700 hover:bg-stone-100 transition-colors"
                          >
                            <Download size={12} />
                            {link.title}
                          </a>
                        ))}
                      </div>
                    ) : null}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : (
        <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-10">
          <div className="lg:col-span-2 space-y-8">
            <div className="bg-white border border-stone-100 rounded-[2rem] p-6 md:p-8 chic-shadow">
              <h3 className="text-2xl font-serif font-bold text-stone-900 mb-6">Your Items</h3>
              <div className="space-y-5">
                {cart.map(({ item, quantity }) => (
                  <div key={item.id} className="flex gap-4 border-b border-stone-100 pb-5 last:border-b-0 last:pb-0">
                    <img src={item.imageUrl} alt={item.title} className="w-20 h-24 rounded-xl object-cover bg-stone-100" />
                    <div className="flex-1">
                      <p className="text-[10px] font-bold uppercase tracking-widest text-stone-400 mb-1">{item.category}</p>
                      <h4 className="font-serif text-lg font-bold text-stone-900 leading-tight">{item.title}</h4>
                      <p className="text-sm text-stone-500">{item.type}</p>
                      <div className="mt-3 flex items-center justify-between">
                        <div className="inline-flex items-center rounded-xl border border-stone-200 overflow-hidden">
                          <button
                            type="button"
                            disabled={isSubmitting}
                            onClick={() => onDecreaseQty(item.id)}
                            className="w-9 h-9 flex items-center justify-center text-stone-700 hover:bg-stone-100 transition-colors disabled:opacity-50"
                          >
                            <Minus size={14} />
                          </button>
                          <span className="w-10 text-center text-sm font-bold text-stone-900">{quantity}</span>
                          <button
                            type="button"
                            disabled={isSubmitting}
                            onClick={() => onIncreaseQty(item.id)}
                            className="w-9 h-9 flex items-center justify-center text-stone-700 hover:bg-stone-100 transition-colors disabled:opacity-50"
                          >
                            <Plus size={14} />
                          </button>
                        </div>
                        <div className="flex items-center gap-4">
                          <p className="font-bold text-stone-900">{formatMoney(item.price * quantity)}</p>
                          <button
                            type="button"
                            disabled={isSubmitting}
                            onClick={() => onRemoveItem(item.id)}
                            className="text-red-500 hover:text-red-600 transition-colors disabled:opacity-50"
                          >
                            <Trash2 size={16} />
                          </button>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="bg-white border border-stone-100 rounded-[2rem] p-6 md:p-8 chic-shadow">
              <h3 className="text-2xl font-serif font-bold text-stone-900 mb-6">Billing Details</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <input
                    type="text"
                    placeholder="Full Name"
                    disabled={isSubmitting}
                    value={form.fullName}
                    onChange={(e) => updateField('fullName', e.target.value)}
                    className="w-full p-4 bg-white border border-stone-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:opacity-60"
                  />
                  {errors.fullName && <p className="text-xs text-red-500 mt-1">{errors.fullName}</p>}
                </div>
                <div>
                  <input
                    type="email"
                    placeholder="Email Address"
                    disabled={isSubmitting}
                    value={form.email}
                    onChange={(e) => updateField('email', e.target.value)}
                    className="w-full p-4 bg-white border border-stone-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:opacity-60"
                  />
                  {errors.email && <p className="text-xs text-red-500 mt-1">{errors.email}</p>}
                </div>
                <div className="md:col-span-2">
                  <input
                    type="text"
                    placeholder="Address"
                    disabled={isSubmitting}
                    value={form.addressLine}
                    onChange={(e) => updateField('addressLine', e.target.value)}
                    className="w-full p-4 bg-white border border-stone-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:opacity-60"
                  />
                  {errors.addressLine && <p className="text-xs text-red-500 mt-1">{errors.addressLine}</p>}
                </div>
                <div>
                  <input
                    type="text"
                    placeholder="Country"
                    disabled={isSubmitting}
                    value={form.country}
                    onChange={(e) => updateField('country', e.target.value)}
                    className="w-full p-4 bg-white border border-stone-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:opacity-60"
                  />
                  {errors.country && <p className="text-xs text-red-500 mt-1">{errors.country}</p>}
                </div>
                <div>
                  <input
                    type="text"
                    placeholder="State"
                    disabled={isSubmitting}
                    value={form.state}
                    onChange={(e) => updateField('state', e.target.value)}
                    className="w-full p-4 bg-white border border-stone-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:opacity-60"
                  />
                  {errors.state && <p className="text-xs text-red-500 mt-1">{errors.state}</p>}
                </div>
                <div>
                  <input
                    type="text"
                    placeholder="City"
                    disabled={isSubmitting}
                    value={form.city}
                    onChange={(e) => updateField('city', e.target.value)}
                    className="w-full p-4 bg-white border border-stone-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:opacity-60"
                  />
                  {errors.city && <p className="text-xs text-red-500 mt-1">{errors.city}</p>}
                </div>
                <div>
                  <input
                    type="text"
                    placeholder="Postal Code"
                    disabled={isSubmitting}
                    value={form.postalCode}
                    onChange={(e) => updateField('postalCode', e.target.value)}
                    className="w-full p-4 bg-white border border-stone-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-stone-200 disabled:opacity-60"
                  />
                  {errors.postalCode && <p className="text-xs text-red-500 mt-1">{errors.postalCode}</p>}
                </div>
              </div>
            </div>

            {paymentRequired && (
              <div className="bg-white border border-stone-100 rounded-[2rem] p-6 md:p-8 chic-shadow">
                <h3 className="text-2xl font-serif font-bold text-stone-900 mb-4">Frontend-Only Mode</h3>
                <p className="text-stone-600 text-sm leading-relaxed">
                  This checkout is disconnected from the backend. No API request or real payment charge is performed.
                </p>
              </div>
            )}
          </div>

          <aside className="lg:col-span-1">
            <div className="bg-white border border-stone-100 rounded-[2rem] p-6 md:p-8 sticky top-28 chic-shadow">
              <h3 className="text-2xl font-serif font-bold text-stone-900 mb-6">Order Total</h3>
              <div className="space-y-3 text-sm">
                <div className="flex justify-between text-stone-600">
                  <span>Subtotal</span>
                  <span>{formatMoney(subtotal)}</span>
                </div>
                <div className="flex justify-between text-stone-600">
                  <span>Tax</span>
                  <span>{formatMoney(tax)}</span>
                </div>
                <div className="pt-3 border-t border-stone-200 flex justify-between text-stone-900 font-bold text-base">
                  <span>Total</span>
                  <span>{formatMoney(total)}</span>
                </div>
              </div>

              <label className="flex items-start gap-3 mt-6 text-sm text-stone-600">
                <input
                  type="checkbox"
                  disabled={isSubmitting}
                  checked={form.agreeToTerms}
                  onChange={(e) => updateField('agreeToTerms', e.target.checked)}
                  className="mt-0.5"
                />
                <span>I agree to the purchase terms and immediate digital delivery policy.</span>
              </label>
              {errors.agreeToTerms && <p className="text-xs text-red-500 mt-1">{errors.agreeToTerms}</p>}

              {paymentError && (
                <p className="mt-4 text-xs text-red-600 bg-red-50 border border-red-100 rounded-lg px-3 py-2">
                  {paymentError}
                </p>
              )}

              <button
                type="submit"
                disabled={isSubmitting}
                className="w-full mt-6 bg-stone-900 text-white py-4 rounded-2xl text-xs font-bold uppercase tracking-widest hover:bg-stone-800 transition-all disabled:opacity-60 disabled:cursor-not-allowed"
              >
                {isSubmitting ? 'Processing...' : `Complete Order ${formatMoney(total)}`}
              </button>

              <div className="mt-5 space-y-3 text-xs text-stone-500">
                <p className="flex items-center gap-2"><Lock size={14} /> Local checkout only</p>
                <p className="flex items-center gap-2"><ShieldCheck size={14} /> Instant local delivery links</p>
              </div>
            </div>
          </aside>
        </form>
      )}
    </section>
  );
};

export default Checkout;
